pipeline{
  agent any

  stages{

    stage('Init'){
      steps{
        echo "Pipeline triggered from GIT!"
        echo "Repository: ${env.GIT_URL}"
        echo "BRANCH : ${env.GIT_BRANCH}"
      }
    }
     
    stage('Test'){
      steps{
        echo "Running tests ....."
      }
    }

    stage('Build'){
      steps{
        echo "Building the stages"
      }
    }
    stage('Package'){
      steps{
        echo "Packaging artifact ...."
        sh '''
          mkdir -p build
          echo "artifact-${BUILD_NUMBER}" > build/output.txt
          '''
        sh "tar -czf artifact-${BUILD_NUMBER}.tar.gz build/"
        archiveArtifacts "artifact-${BUILD_NUMBER}.tar.gz"
      }
    }
      
  }
  
  post{
      success{
        echo "Pipeline completed successfully"
      }

      failure{
        echo "Pipeline has failed"
        }

      always{
          cleanWs()
        }
      }
  
}
