name: Assignment-secret

on: push

jobs:
  secret-practice:
    runs-on: ubuntu-latest

    steps:
        - name: Print secrets
          run: |
            echo "Employee ID is $EMP_ID"
            echo "Employee Location is $LOCATION"
          env:
            EMP_ID: ${{ secrets.EMP_ID }}
            LOCATION: ${{ secrets.LOCATION }}
        
        - name: Create info.txt
          run: echo "ID: $EMP_ID, LOCATION: $LOCATION" > info.txt
          env:
            EMP_ID: ${{ secrets.EMP_ID }}
            LOCATION: ${{ secrets.LOCATION }}
        
        - name: Upload info.txt
          uses: actions/upload-artifact@v4
          with:
            name: secret-info
            path: info.txt








          
              
