name: Output of this

on: push

jobs:
  JOB_A:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.ver.outputs.tag}}
    steps:
      - id: ver
        run: echo "tag=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

        name: Output_check
  JOB_B:
    runs-on: ubuntu-latest
    needs: JOB_A
    steps:
      - run: |
          echo "Output received: ${{ needs.JOB_A.outputs.tag}}"

