name: Hello workflow

on: 
  push:
    branches: ["main"]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello Prajwal, this is your first Pipeline"
