name: Multi-build-assignment

on: push

jobs:
  Job_A:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job A"

  Job_B:
    runs-on: ubuntu-latest
    needs: Job_A
    steps:
      - run: echo "Job B"
  Job_C:
    runs-on: ubuntu-latest
    needs: Job_B
    steps:
      - run: echo "Job C"
