name: trigger-demo

on: 
  push: 
    branches: ["main"]

  pull_request:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  test-triggers:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Triggered by : ${{ github.event_name }}"
      
  
